# These are supported funding model platforms

github: mobilex1122 # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: mobilex # Replace with a single Patreon username
